#!/bin/zsh
# shellcheck shell=bash

# Set up CyHy docker environment variables
export CYHY_CONF_DIR=/private/etc/cyhy
export CYHY_CORE_IMAGE=ncats/cyhy-core

# Set up CyHy aliases
eval "$(docker run ncats/cyhy-core)"

